# Generated by Django 3.0.5 on 2021-05-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lung_photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/breast')),
            ],
        ),
        migrations.CreateModel(
            name='skin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/breast')),
            ],
        ),
    ]
