# Generated by Django 3.0.5 on 2021-05-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lung_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lung',
            name='lung_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/lung/input/input'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='skin_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/skin/input'),
        ),
    ]
