# Generated by Django 3.0.5 on 2021-05-21 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_riskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmodel',
            name='skin_lesions',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
