# Generated by Django 3.0.5 on 2021-05-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
